Repository DhairyaBahl/React-Messenger-App, pull requests merged in 2021-05, with the labels that each got.

#171 Contactform frontend
  src/App.js
  src/components/contactForm/contactForm.css
  src/components/contactForm/contactForm.js
Labels: Level3, gssoc21

#193 Fixed issue: Messages not loading
  package-lock.json
  src/components/messages/Messages.js
Labels: gssoc21

#197 Navbar ui modified
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#198 Size reduced of footer on about us page.
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: Level2, gssoc21

#199 Contact us form modified.
  src/components/contactForm/contactForm.css
  src/components/contactForm/contactForm.js
Labels: Level2, gssoc21

#203 Fixed the twitter link of footer
  src/components/footer/footer.js
Labels: gssoc21

#204 Added email validation in contact-us form
  src/components/contactForm/contactForm.js
Labels: Level2, gssoc21

#210 Fixed Emoji Insertion Bug
  src/App.js
Labels: gssoc21

#213 Added a landing page
  src/App.js
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
  src/components/Landingpage/sideimage.png
Labels: Level3, gssoc21

#222 Theme change is now working for contact us form.
  src/App.js
  src/components/contactForm/contactForm.css
  src/components/contactForm/contactForm.js
Labels: gssoc21

#218 Added Speech to text input.
  package-lock.json
  package.json
  src/App.js
Labels: Level3, gssoc21

#235 Added the Feature page
  src/App.css
  src/App.js
  src/components/Featurespage/FeaturesPage.css
  src/components/Featurespage/FeaturesPage.jsx
  src/components/Featurespage/blacktheme.png
  src/components/Featurespage/emoji.png
  src/components/Featurespage/sideimage.png
Labels: Level3, gssoc21

#231 Fixed navmenu theme in mobile view.
  src/App.css
  src/App.js
Labels: gssoc21

#236 enhance the styling of audio button
  src/App.css
Labels: Level3, gssoc21

#232 changed FAQ data into array of objects and mapped over it
  src/components/faq/faq.js
Labels: gssoc21

#228 Button styling issue fixed
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level2, gssoc21

#224 Remove unnecessary comments and add useful comments
  src/App.js
  src/components/Landingpage/LandingPage.jsx
  src/components/contactForm/contactForm.js
  src/components/footer/footer.js
  src/components/messages/Messages.js
Labels: Level1, gssoc21

#234 Added Scroll to bottom button
  src/App.js
Labels: Level2, gssoc21

#244 Compilation error fixed
  src/App.js
Labels: Level2, gssoc21

#249 set up eslint and prettier code
  .eslintrc.js
  package-lock.json
  package.json
Labels: Level3, gssoc21

#246 Added dark theme support for feature page
  src/App.js
  src/components/Featurespage/FeaturesPage.css
  src/components/Featurespage/FeaturesPage.jsx
Labels: Level2, gssoc21

#245 Footer theme switch fixed.
  src/App.js
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: Level2, gssoc21

#247 handled dropdown of cards by using custom function
  src/components/faq/faq.js
Labels: gssoc21

#253 fixed the rules of eslint setup
  .eslintrc.js
  src/components/contactForm/contactForm.js
Labels: Level2, gssoc21

#260 Added dark theme for FAQ section.
  src/App.js
  src/components/faq/faq.css
  src/components/faq/faq.js
Labels: Level2, gssoc21

#258 Speak now alert added
  package-lock.json
  src/App.css
  src/App.js
Labels: gssoc21

#269 Fixed Responsiveness in Features Page
  src/App.css
  src/components/Featurespage/FeaturesPage.css
Labels: Level2, gssoc21

#268 Landing page in both light and dark mode.
  src/App.js
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level2, gssoc21

#265 made sender's name visible
  src/components/messages/Messages.css
Labels: Level2, gssoc21

#239 Hiding api keys
  .gitignore
  src/firebase.js
Labels: Level3, gssoc21

#251 fixed css prefixes for cross browser compatibility
  src/components/Featurespage/FeaturesPage.css
Labels: Level2, gssoc21

#267 the dropdown arrow key(scroll to bottom) added to the bottom right corner
  package-lock.json
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#274 Welcome Dialogue Box Submits on Pressing Enter Key
  src/WelcomeDialogBox.js
Labels: Level2, gssoc21

#278 added dark themed input box
  src/App.css
  src/App.js
Labels: gssoc21

#273 Code cleaned.
  src/App.css
  src/App.js
  src/components/Featurespage/FeaturesPage.css
  src/components/Featurespage/FeaturesPage.jsx
  src/components/Landingpage/LandingPage.css
  src/components/about-us/Abouts.css
  src/components/contactForm/contactForm.css
  src/components/contactForm/contactForm.js
  src/components/messages/Messages.css
  src/switcher.css
Labels: Level2, gssoc21

#279 Added Space between Input Area and Latest Message
  src/App.js
Labels: Level2, gssoc21

#280 Load Latest 50 Messages only at the Start
  src/App.js
Labels: Level3, gssoc21

#277 fixed the font size
  src/App.css
  src/components/messages/Messages.css
Labels: Level2, gssoc21

#291 Implemented Load Older Messages Button
  src/App.css
  src/App.js
Labels: gssoc21

#298 adding dark theme to footer of feature page
  src/App.js
Labels: Level2, gssoc21

#300 Dark theme to footer of login page
  src/App.js
Labels: Level2, gssoc21

#306 Issue #305
  README.md
Labels: Level3, gssoc21

#314 Fixed mis-ordered text on About page
  src/components/about-us/About.js
Labels: Level2, gssoc21

#312 Scroll button
  src/App.css
  src/App.js
  src/components/footer/footer.js
Labels: Level2, gssoc21

#301 adding dynamic year to footer
  src/components/footer/footer.js
Labels: gssoc21

#308 implemented code splitting
  src/App.js
Labels: Level3, gssoc21

#304 Made Scroll to Bottom Button Visible and Usable on Narrow Screens
  src/App.css
Labels: Level2, gssoc21

#323 Messages bug solved!
  src/App.js
Labels: Level3, gssoc21

#326 Added Local Storage for user details & preferences
  src/App.js
  src/customHooks/useLocalStorage.js
Labels: Level3, gssoc21

#327 Content of the message input field aligned to center
  src/App.css
Labels: Level2, gssoc21

#337 About us text size fixed
  src/components/Featurespage/FeaturesPage.css
Labels: Level2, gssoc21

#338 navbar lightmode size fixed
  src/App.css
Labels: Level2, gssoc21

#340 footer bug fixed
  src/components/footer/footer.css
Labels: Level2, gssoc21

#344 enabled socket connection between client and server
  socket-io-client/.gitignore
  socket-io-client/README.md
  socket-io-client/package-lock.json
  socket-io-client/package.json
  socket-io-client/public/favicon.ico
  socket-io-client/public/index.html
  socket-io-client/public/logo192.png
  socket-io-client/public/logo512.png
  socket-io-client/public/manifest.json
  socket-io-client/public/robots.txt
  socket-io-client/src/App.css
  socket-io-client/src/App.js
  socket-io-client/src/App.test.js
  socket-io-client/src/index.css
  socket-io-client/src/index.js
  socket-io-client/src/logo.svg
  socket-io-client/src/reportWebVitals.js
  socket-io-client/src/setupTests.js
  socket-io-client/yarn.lock
Labels: Level3, gssoc21

#347 images optimized by more than 50%
  src/components/Featurespage/blacktheme.png
  src/components/Featurespage/emoji.png
  src/components/Featurespage/sideimage.png
Labels: Level2, gssoc21

#350 timestamp colour changed
  src/components/messages/Messages.css
Labels: Level2, gssoc21

#352 added secondary texts, both dark and light mode
  src/components/Featurespage/FeaturesPage.jsx
Labels: Level2, gssoc21

#342 Custom background about
  src/App.js
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: Level3, gssoc21

#351 made navbar equal in both light and dark theme!
  src/App.css
Labels: Level2, gssoc21

#354 upload files and images or documents
  file-upload/.gitignore
  file-upload/README.md
  file-upload/package-lock.json
  file-upload/package.json
  file-upload/public/favicon.ico
  file-upload/public/index.html
  file-upload/public/logo192.png
  file-upload/public/logo512.png
  file-upload/public/manifest.json
  file-upload/public/robots.txt
  file-upload/src/App.css
  file-upload/src/App.js
  file-upload/src/App.test.js
  file-upload/src/index.css
  file-upload/src/index.js
  file-upload/src/logo.svg
  file-upload/src/reportWebVitals.js
  file-upload/src/setupTests.js
  file-upload/yarn.lock
Labels: Level3, gssoc21

#356 Added onscreen keyboard
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: Level3, gssoc21

#360 Landing page contents aligned.
  src/App.js
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level3, gssoc21

#349 increased the size of theme icon
  src/App.js
Labels: Level2, gssoc21

#363 Added dark theme for login form.
  src/App.js
  src/components/login/login.css
  src/components/login/login.jsx
Labels: Level2, gssoc21

#366 Navbar mobile
  src/App.css
Labels: Level2, gssoc21

#362 Footer text issue fixed.
  src/App.js
Labels: gssoc21

#369 Onscreen keyboard in dark issue fixed.
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#370 Font size fixed of message box.
  src/components/messages/Messages.css
Labels: gssoc21

#372 Enhanced styling of onscreen_keyboard icon.
  src/App.css
Labels: Level2, gssoc21

#373 Added dark theme in footer of landing page.
  src/App.js
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level2, gssoc21

#375 Postion of emoji picker fixed in dark mode.
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#374 Added signup page
  src/App.js
  src/components/signup/logo.png
  src/components/signup/signup.css
  src/components/signup/signup.jsx
Labels: Level3, gssoc21

#376 added react profile avatar icon besides message
  react-avatar/.babelrc
  react-avatar/.editorconfig
  react-avatar/.gitignore
  react-avatar/.npmignore
  react-avatar/docs/bundle.js
  react-avatar/docs/einshtein.jpg
  react-avatar/docs/example.gif
  react-avatar/docs/index.html
  react-avatar/docs/user.png
  react-avatar/example/app.jsx
  react-avatar/example/index.html
  react-avatar/package-lock.json
  react-avatar/package.json
  react-avatar/src/avatar.d.ts
  react-avatar/src/avatar.jsx
  react-avatar/webpack.dev.js
  react-avatar/webpack.example.js
  react-avatar/webpack.prod.js
Labels: Level3, gssoc21

#380 Button effects
  src/App.css
  src/about-1.svg
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: Level2, gssoc21

#378 about us illustrations developed
  src/about-1.svg
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: gssoc21

#384 store messages in local storage
  src/App.js
Labels: Level3, gssoc21

#391 about motive redesigned
  src/about-2.svg
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: Level3, gssoc21

#392 custom dark and light mode background
  src/components/faq/faq.css
  src/components/faq/faq.js
Labels: Level3, gssoc21

#395 Fix nav links for dark mode
  src/App.css
Labels: Level2, gssoc21

#400 Hover style to footer logo
  src/components/footer/footer.css
Labels: Level2, gssoc21

#401 added shadow to footer
  src/components/footer/footer.css
Labels: Level2, gssoc21

#402 Styled FAQ text
  src/components/faq/faq.css
  src/components/faq/faq.js
Labels: Level2, gssoc21

#412 Added route to pages
  src/components/login/login.jsx
  src/components/signup/signup.jsx
Labels: Level2, gssoc21

#414 #413 Fix the sign-up page footer in dark mode
  package-lock.json
  src/App.js
Labels: Level2, gssoc21

#418 Compilation error fixed.
  src/components/faq/faq.js
Labels: gssoc21

#415 Added Forgot Password Page [FrontEnd]
  src/App.js
  src/components/forgetpass/forget.css
  src/components/forgetpass/forget.jsx
  src/components/forgetpass/forget.png
  src/components/login/login.jsx
Labels: Level3, gssoc21

#420 fixed the font size of icons in footer
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: Level2, gssoc21

#422 Adding Push notifications to chat web app
  firebase-notifications/fire_client/.gitignore
  firebase-notifications/fire_client/README.md
  firebase-notifications/fire_client/package-lock.json
  firebase-notifications/fire_client/package.json
  firebase-notifications/fire_client/public/firebase-messaging-sw.js
  firebase-notifications/fire_client/public/index.html
  firebase-notifications/fire_client/src/App.js
  firebase-notifications/fire_client/src/firebase.js
  firebase-notifications/fire_client/src/index.js
  firebase-notifications/fire_client/yarn.lock
  package-lock.json
  package.json
Labels: Level3, gssoc21

#425 Added reset password page
  src/App.js
  src/components/forgetpass/forget.jsx
  src/components/resetpass/reset.css
  src/components/resetpass/reset.jsx
Labels: Level3, gssoc21

#426 Fixed Dark Mode of Login & Signup Page
  src/App.js
  src/components/login/login.css
  src/components/login/login.jsx
  src/components/signup/signup.css
  src/components/signup/signup.jsx
Labels: Level2, gssoc21

#427 Features page issue fixed.
  src/components/Featurespage/FeaturesPage.css
Labels: Level2, gssoc21

#429 Added a top-loading bar.
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: Level3, gssoc21

#436 Added floating animation to feature page.
  src/components/Featurespage/FeaturesPage.css
  src/components/Featurespage/FeaturesPage.jsx
Labels: Level2, gssoc21

#437 Size of landing page fixed.
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level2, gssoc21

#439 Styled typing space icons on HOME
  src/App.css
Labels: Level2, gssoc21

#441 Added email-auto complete.
  package-lock.json
  package.json
  src/components/signup/signup.jsx
Labels: Level3, gssoc21

#444 signin and signup page
  SignIn-Signup/firebase-auth-app/.gitignore
  SignIn-Signup/firebase-auth-app/README.md
  SignIn-Signup/firebase-auth-app/package.json
  SignIn-Signup/firebase-auth-app/public/index.html
  SignIn-Signup/firebase-auth-app/src/App.js
  SignIn-Signup/firebase-auth-app/src/Components/Application.js
  SignIn-Signup/firebase-auth-app/src/Components/PaaswordReset.js
  SignIn-Signup/firebase-auth-app/src/Components/ProfilePage.js
  SignIn-Signup/firebase-auth-app/src/Components/SignIn.js
  SignIn-Signup/firebase-auth-app/src/Components/SignUp.js
  SignIn-Signup/firebase-auth-app/src/firebase.js
  SignIn-Signup/firebase-auth-app/src/providers/UserProvider.js
  SignIn-Signup/firebase-auth-app/yarn.lock
Labels: gssoc21

#438 Styled button on Home
  src/App.css
Labels: Level2, gssoc21

#466 onboarding screen native added
  Messenger-Native-App/context/assets/adaptive-icon.png
  Messenger-Native-App/context/assets/colors/colors.js
  Messenger-Native-App/context/assets/favicon.png
  Messenger-Native-App/context/assets/fonts/OpenSans-Bold.ttf
  Messenger-Native-App/context/assets/fonts/OpenSans-Regular.ttf
  Messenger-Native-App/context/assets/fonts/OpenSans-SemiBold.ttf
  Messenger-Native-App/context/assets/icon.png
  Messenger-Native-App/context/assets/images/Onboard1.png
  Messenger-Native-App/context/assets/images/Onboard2.png
  Messenger-Native-App/context/assets/images/Onboard3.png
  Messenger-Native-App/context/assets/images/undraw_Moving_twwf.svg
  Messenger-Native-App/context/assets/images/undraw_privacy_protection_nlwy.svg
  Messenger-Native-App/context/assets/images/undraw_unlock_24mb.svg
  Messenger-Native-App/context/assets/onboarding-img1.png
  Messenger-Native-App/context/assets/onboarding-img2.png
  Messenger-Native-App/context/assets/onboarding-img3.png
  Messenger-Native-App/context/assets/splash.png
  Messenger-Native-App/onboarding-screen-native/App.js
  Messenger-Native-App/onboarding-screen-native/app.json
  Messenger-Native-App/onboarding-screen-native/assets/adaptive-icon.png
  Messenger-Native-App/onboarding-screen-native/assets/colors/colors.js
  Messenger-Native-App/onboarding-screen-native/assets/favicon.png
  Messenger-Native-App/onboarding-screen-native/assets/fonts/OpenSans-Bold.ttf
  Messenger-Native-App/onboarding-screen-native/assets/fonts/OpenSans-Regular.ttf
  Messenger-Native-App/onboarding-screen-native/assets/fonts/OpenSans-SemiBold.ttf
  Messenger-Native-App/onboarding-screen-native/assets/icon.png
  Messenger-Native-App/onboarding-screen-native/assets/images/Onboard1.png
  Messenger-Native-App/onboarding-screen-native/assets/images/Onboard2.png
  Messenger-Native-App/onboarding-screen-native/assets/images/Onboard3.png
  Messenger-Native-App/onboarding-screen-native/assets/images/undraw_Moving_twwf.svg
  Messenger-Native-App/onboarding-screen-native/assets/images/undraw_privacy_protection_nlwy.svg
  Messenger-Native-App/onboarding-screen-native/assets/images/undraw_unlock_24mb.svg
  Messenger-Native-App/onboarding-screen-native/assets/onboarding-img1.png
  Messenger-Native-App/onboarding-screen-native/assets/onboarding-img2.png
  Messenger-Native-App/onboarding-screen-native/assets/onboarding-img3.png
  Messenger-Native-App/onboarding-screen-native/assets/splash.png
  Messenger-Native-App/onboarding-screen-native/babel.config.js
  Messenger-Native-App/onboarding-screen-native/components/Home.js
  Messenger-Native-App/onboarding-screen-native/components/Onboarding.js
  Messenger-Native-App/onboarding-screen-native/components/OnboardingScreen.js
  Messenger-Native-App/onboarding-screen-native/package-lock.json
  Messenger-Native-App/onboarding-screen-native/package.json
Labels: Level3, gssoc21

#443 Improved UI of Submit Button
  src/components/forgetpass/forget.css
  src/components/login/login.css
  src/components/resetpass/reset.css
  src/components/signup/signup.css
Labels: Level2, gssoc21

#445 increased the font size of messages in mobile view
  src/components/messages/Messages.css
Labels: gssoc21

#446 Added installation steps in Readme
  README.md
  public/fork_button.jpg
Labels: Level1, gssoc21

#452 Feature copy to clipboard added.
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#457 Floating animation added in landing page.
  src/components/Landingpage/LandingPage.css
Labels: Level2, gssoc21

#467 light and dark theme UI added for native app
  Messenger-Native-App/dark-light-theme/constants.js
  Messenger-Native-App/dark-light-theme/index.js
  Messenger-Native-App/dark-light-theme/propTypes.js
  Messenger-Native-App/dark-light-theme/themes.js
Labels: Level3, gssoc21

#470 Compilation Error fixed
  src/App.js
Labels: Level2, gssoc21

#442 #424 Fix the keyboard toggler button layout in light mode.
  src/App.css
Labels: Level2, gssoc21

#464 Added push-notification feature
  package-lock.json
  package.json
  src/App.js
Labels: Level3, gssoc21

#468 Feature auto complete added in contact us form.
  src/components/contactForm/contactForm.js
Labels: Level2, gssoc21

#471 Native App: custom background added
  Messenger-Native-App/custom-background-native/package.json
  Messenger-Native-App/custom-background-native/public/index.html
  Messenger-Native-App/custom-background-native/public/manifest.json
  Messenger-Native-App/custom-background-native/src/App.js
  Messenger-Native-App/custom-background-native/src/index.css
  Messenger-Native-App/custom-background-native/src/index.js
  Messenger-Native-App/package-lock.json
  Messenger-Native-App/package.json
  Messenger-Native-App/popup-menu-option/examples/popoverexample.js
  Messenger-Native-App/popup-menu-option/mocks/react-native.js
  Messenger-Native-App/popup-menu-option/src/menuoption.js
  Messenger-Native-App/popup-menu-option/tests/Backdrop-test.js
  Messenger-Native-App/popup-menu-option/tests/Menu-test.js
  Messenger-Native-App/popup-menu-option/tests/MenuOption-test.js
  Messenger-Native-App/popup-menu-option/tests/MenuOptions-tests.js
  Messenger-Native-App/popup-menu-option/tests/MenuProvider-test.js
  Messenger-Native-App/popup-menu-option/tests/renderers/ContextMenu-text.js
  Messenger-Native-App/popup-menu-option/tests/renderers/MenuOutside-test.js
  Messenger-Native-App/popup-menu-option/tests/renderers/NotAnimatedContext.js
  Messenger-Native-App/popup-menu-option/tests/renderers/SlideInMenu-test.js
  Messenger-Native-App/popup-menu-option/tests/renderers/popover-test.js
  Messenger-Native-App/yarn.lock
Labels: Level3, gssoc21

#473 custom background for individual faqs
  src/components/faq/faq.css
  src/components/faq/faq.js
Labels: Level2, gssoc21

#516 Login illustration
  src/App.css
  src/components/about-us/Abouts.css
  src/components/login/login.css
  src/components/login/login.jsx
  src/components/login/logo.png
  src/components/login/logo1.svg
Labels: Level3, gssoc21

#475 tagging previous message and react-mentions
  react-mentions/demo/src/examples/BottomGuard.js
  react-mentions/demo/src/index.html
  react-mentions/demo/src/index.js
  react-mentions/src/Mention.js
  react-mentions/src/MentionInput.js
Labels: Level3, gssoc21

#478 additional multicolour themes added
  additional-themes/package-lock.json
  additional-themes/package.json
  additional-themes/pages/_app.js
  additional-themes/pages/_document.js
  additional-themes/pages/colourTheme.js
  additional-themes/pages/index.js
Labels: Level3, gssoc21

#483 feature authentication and chat group users implementation
  chat-group-authentication/react-pusher/.gitignore
  chat-group-authentication/react-pusher/README.md
  chat-group-authentication/react-pusher/package-lock.json
  chat-group-authentication/react-pusher/package.json
  chat-group-authentication/react-pusher/public/favicon.ico
  chat-group-authentication/react-pusher/public/index.html
  chat-group-authentication/react-pusher/public/logo192.png
  chat-group-authentication/react-pusher/public/logo512.png
  chat-group-authentication/react-pusher/public/manifest.json
  chat-group-authentication/react-pusher/public/robots.txt
  chat-group-authentication/react-pusher/src/App.css
  chat-group-authentication/react-pusher/src/App.js
  chat-group-authentication/react-pusher/src/App.test.js
  chat-group-authentication/react-pusher/src/Auth.js
  chat-group-authentication/react-pusher/src/Callback.js
  chat-group-authentication/react-pusher/src/Chat.js
  chat-group-authentication/react-pusher/src/Home.js
  chat-group-authentication/react-pusher/src/Profile.js
  chat-group-authentication/react-pusher/src/Profile/profile.css
  chat-group-authentication/react-pusher/src/auth0-variables.js
  chat-group-authentication/react-pusher/src/history.js
  chat-group-authentication/react-pusher/src/index.css
  chat-group-authentication/react-pusher/src/index.js
  chat-group-authentication/react-pusher/src/logo.svg
  chat-group-authentication/react-pusher/src/reportWebVitals.js
  chat-group-authentication/react-pusher/src/routes.js
  chat-group-authentication/react-pusher/src/server.js
  chat-group-authentication/react-pusher/src/setupTests.js
  chat-group-authentication/react-pusher/yarn.lock
Labels: Level3, gssoc21

#507 Compilation error fixed
  src/App.js
Labels: Level2, gssoc21

#513 Landing page mobile image removed for smaller devices
  src/components/Landingpage/LandingPage.css
Labels: Level2, gssoc21

#486 Hover to footer logo
  src/components/footer/footer.css
  src/components/footer/footer.js
Labels: Level2, gssoc21

#487 Aligned footer text
  src/components/footer/footer.css
Labels: Level2, gssoc21

#489 Changed color for dark text
  src/components/Featurespage/FeaturesPage.css
  src/components/Featurespage/FeaturesPage.jsx
  src/components/Landingpage/LandingPage.css
  src/components/Landingpage/LandingPage.jsx
Labels: Level2, gssoc21

#495 increase the size of faq's in mobile view
  src/components/faq/faq.css
  src/components/faq/faq.js
Labels: Level2, gssoc21

#496 preloader made
  src/components/preloader/preloader.jsx
  src/components/preloader/styles.css
Labels: Level3, gssoc21

#505 Fixed visibility of text in dark mode
  src/App.css
Labels: Level2, gssoc21

#508 Styled Enter chat button
  src/components/Landingpage/LandingPage.css
Labels: Level2, gssoc21

#509 updated messages color scheme
  src/components/messages/Messages.css
Labels: Level2, gssoc21

#524 increased the size of navbar in dark theme
  src/App.css
Labels: Level2, gssoc21

#499 Signup responsive
  src/components/login/login.css
  src/components/signup/signup.css
Labels: Level2, gssoc21

#544 email field issue in dark mode fixed
  src/components/signup/signup.css
  src/components/signup/signup.jsx
Labels: Level2, gssoc21

#523 sign up page dark mode footer
  src/components/footer/footer.css
Labels: Level2, gssoc21

#545 mobile change theme button
  src/App.css
Labels: Level3, gssoc21

#518 Fixed Overlapping
  src/components/faq/faq.js
Labels: Level2, gssoc21

#543 Dark theme issue of login page fixed.
  package-lock.json
  src/components/login/login.css
  src/components/login/login.jsx
Labels: Level2, gssoc21

#556 mobile support application for the app
  flickrapp/app/components/app.jsx
Labels: Level3, gssoc21

#557 performance optimization of the app and making it faster
  performance-optimization/app.js
  performance-optimization/react-messenger/.gitignore
  performance-optimization/react-messenger/App.js
  performance-optimization/react-messenger/README.md
  performance-optimization/react-messenger/package.json
  performance-optimization/react-messenger/public/favicon.ico
  performance-optimization/react-messenger/public/index.html
  performance-optimization/react-messenger/public/logo192.png
  performance-optimization/react-messenger/public/logo512.png
  performance-optimization/react-messenger/public/manifest.json
  performance-optimization/react-messenger/public/robots.txt
  performance-optimization/react-messenger/src/App.css
  performance-optimization/react-messenger/src/App.test.js
  performance-optimization/react-messenger/src/components/Infopane.js
  performance-optimization/react-messenger/src/components/home.js
  performance-optimization/react-messenger/src/index.css
  performance-optimization/react-messenger/src/index.js
  performance-optimization/react-messenger/src/logo.svg
  performance-optimization/react-messenger/src/reportWebVitals.js
  performance-optimization/react-messenger/src/setupTests.js
  performance-optimization/react-messenger/yarn.lock
Labels: Level3, gssoc21

#560 Fixed Overlapping of Scroll to Bottom Button with Input Field
  src/App.css
  src/components/login/login.jsx
  src/components/signup/signup.jsx
Labels: Level2, gssoc21

#559 Compilation error fixed.
  src/components/login/login.jsx
  src/components/signup/signup.jsx
Labels: Level2, gssoc21

#582 about-hero1-animation
  package-lock.json
  package.json
  src/components/about-us/About.js
Labels: Level2, gssoc21

#580 Fixed Navigation menu
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#598 multiple markup patterns
  markup_patterns/index.js
  markup_patterns/provideExamplevalue.js
Labels: Level3, gssoc21

#592 UI improvement done
  UI-styling/beautiful-UI-react.yml
  UI-styling/codestyleconfig.xml
  styles-header/index.js
  styles-header/styles.js
Labels: Level3, gssoc21

#563 added new styles header to app
  styles-header/index.js
  styles-header/styles.js
Labels: gssoc21

#562 Added Illustration for Forgot Password Page
  src/components/forgetpass/forget.css
  src/components/forgetpass/forget.jsx
  src/components/forgetpass/forget.svg
Labels: Level3, gssoc21

#573 Load older messages button modified
  src/App.css
Labels: Level2, gssoc21

#574 Fixed logo size
  src/App.css
Labels: Level2, gssoc21

#575 Fixed nav icon
  src/App.css
Labels: Level2, gssoc21

#577 Fixed navigation gap
  src/App.css
Labels: gssoc21

#581 Fixed About us on mobile.
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: Level2, gssoc21

#591 Added status copied after the text is copied.
  src/App.css
  src/App.js
Labels: Level2, gssoc21

#604 Size of message input field in dark mode fixed.
  src/App.css
Labels: Level2, gssoc21

#605 Added email auto complete feature in forgot password.
  package-lock.json
  src/components/forgetpass/forget.jsx
Labels: Level3, gssoc21
