Repository DhairyaBahl/React-Messenger-App, pull requests merged in 2021-04, with the labels that each got.

#121 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Level1, gssoc21

#131 Multicolor themes added
  .eslintcache
  .gitignore
  package.json
  src/App.js
  src/components/Button.js
  src/components/messages/Messages.css
  src/index.css
  src/switcher.css
Labels: Level3, gssoc21

#142 hamburger navbar | about us, home | new UI
  src/App.css
  src/App.js
Labels: Level3, gssoc21

#143 Footer Enhancement
  .eslintcache
  package-lock.json
  src/App.css
  src/App.js
Labels: Level3, gssoc21

#146 About us page
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/about-us/About.js
  src/components/about-us/Abouts.css
Labels: Level3, gssoc21

#165 Inputbox made responsive
  src/App.css
Labels: Level2, gssoc21
